source = $HOME/.config/hypr/mocha.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = JetBrainsMono Nerd Font

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = $HOME/.config/background
  blur_passes = 0
  color = $base
}

# LAYOUT
label {
  monitor =
  text = Konnichiwa!!
  color = $text
  font_size = 25
  font_family = $font
  position = 30, -30
  halign = left
  valign = top
}

# TIME
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 120
  font_family = $font
  position = -710, -250
  halign = right
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 30
  font_family = $font
  position = -635, -450
  halign = right
  valign = top
}

# USER AVATAR
image {
  monitor =
  path = $HOME/.face
  size = 100
  # border_color = $accent
  position = -150, -80
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 90, -85
  halign = center
  valign = center
}

# Degrees
label {
    monitor =
    # text = cmd[update:18000000] echo "<b>Feels like<big> $(curl -s 'wttr.in?format=%t' | tr -d '+') </big></b>"
    text = cmd[update:18000000] echo "$(curl -s 'wttr.in?format=%t' | tr -d '+')"
    # text = cmd[update:18000000] curl "wttr.in/Pune?format=3"
    color = $text
    font_size = 25
    font_family = $font

    position = 0, 40
    halign = center
    valign = bottom